### PR TITLE
Update to react 0.14.0-beta2

### PR DESCRIPTION
**Pull request by shernshiou**
Preparing react-jade for new 0.14.0 version

### CODE REVIEW

**Comment by ai** [comment]
@hemanth React 0.14 released. So this PR is now very important.

**Comment by ForbesLindesay** [comment]
Looking at this, there's nothing here that actually affects us.  react-jade already works with react 0.14 as none of the breaking changes impacted react-jade.  There's not even any reason to release a new version.

**Comment by ai** [comment]
@ForbesLindesay there is a `react` version requirement in `react-jade` `package.json`, so npm told me about conflict.

**Comment by ForbesLindesay** [comment]
Ah, I missed that you had removed the `peerDependencies`.  I'll re-add those and then publish a new version.

**Comment by hemanth** [comment]
:+1:

**Comment by shernshiou** [comment]
Thanks all.

**Pull request merged**
